title: Pascal van Eck
author: Pascal van Eck
description: Pascal's personal website
remote_theme: daattali/beautiful-jekyll

navbar-links:
  Home: home
  About Me: about-me
  Publications:
    - Selected publications: /publications
    - Thesis: /publications/thesis
  Blog: blog

avatar: "/assets/img/avatar-icon.png"
round-avatar: true

social-network-links:
  email: "pascal@pascalvaneck.com"
  github: patveck
  twitter: patveck
  linkedin: pascalvaneck
  google-scholar: "citations?user=PEnurM4AAAAJ&hl=en"

url-pretty: "pascalvaneck.com"  

google_analytics: G-KR1XCXHDNX

date_format: "%B %-d, %Y"
timezone: Europe/Amsterdam
permalink: /:year-:month-:day-:title/
paginate: 5
paginate_path: "/blog/page:num/"

markdown: kramdown
highlighter: rouge
kmarkdown:
  input: GFM

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
